### ISSUE TITLE
我好像重复造轮子了

### ISSUE THREAD

**Issue by rachpt** [Dawnnnnnn/Cloud189#1]
https://github.com/Aruelius/cloud189/issues/10
:angry:

https://github.com/rachpt/cloud189

**Comment by Dawnnnnnn** [comment]
不一样的，[Aruelius/cloud189](https://github.com/Aruelius/cloud189) 项目是靠网页端API完成操作的，我这个是逆向的Mac下的天翼网盘客户端，理论上比网页端支持的功能要多，比如断点续传和秒传。且我坚信天翼网盘会发展成网页下载大文件需要客户端的结果，先做了没啥不好的
