### ISSUE TITLE
上传过程中会卡死

### ISSUE THREAD

**Issue by linker999** [Dawnnnnnn/Cloud189#3]
好久不动了，也不是在上传

![QQ图片20200520183137](https://user-images.githubusercontent.com/55228893/82436313-3285fd00-9ac8-11ea-9e36-b48e80974168.png)

**Comment by Dawnnnnnn** [comment]
你是不是网络不稳定...还是ip在一直跳？上传节点一会贵州一会重庆一会江西一会云南，这也太广了，我传文件只有同一个省的节点啊。。

**Comment by linker999** [comment]
> 你是不是网络不稳定...还是ip在一直跳？上传节点一会贵州一会重庆一会江西一会云南，这也太广了，我传文件只有同一个省的节点啊。。

我用群晖系统上传的 ip不会变阿

**Comment by Dawnnnnnn** [comment]
看日志就是网络问题卡住了，代码里没加默认超时时间，我加个吧
