### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by linker999** [Dawnnnnnn/Cloud189#4]

**Comment by Dawnnnnnn** [comment]
还能复现吗

**Comment by linker999** [comment]
> 还能复现吗

复现不了，现在删掉程序再放下去操作也是从SE06上传出现这个错误。
之前是照常上传但是到SE06就出现这个错误。。

**Comment by Dawnnnnnn** [comment]
emmmm? SE06是什么

**Comment by linker999** [comment]
> emmmm? SE06是什么

上面的文件名。The.Adventures.of Sherlock.Holmes.1984.SE06.BluRay.iPad.720p.AAC.x264

**Comment by Dawnnnnnn** [comment]
还能出现错误就是能复现呀...现在再上传SE06也报这个吗

**Comment by linker999** [comment]
> 还能出现错误就是能复现呀...现在再上传SE06也报这个吗

是的 删掉程序 再下载 重新登陆账号也是从SE06开始上传 然后报错误

**Comment by Dawnnnnnn** [comment]
那我发个debug版本你试试

**Comment by linker999** [comment]
> 那我发个debug版本你试试

![微信图片_20200520220242](https://user-images.githubusercontent.com/55228893/82459852-ff089a00-9aea-11ea-9c2a-4f5ee0a6c70b.png)

**Comment by Dawnnnnnn** [comment]
啊这
{"res_message": "UserDayFlowOverLimited" , "res code": "UserDayFlowOverLimited"}
你账号超出每日上传限制了

**Comment by linker999** [comment]
> 啊这
> {"res_message": "UserDayFlowOverLimited" , "res code": "UserDayFlowOverLimited"}
> 你账号超出每日上传限制了

好像是这个错误 ，没想到测着测着 就用完200G了。

**Comment by linker999** [comment]
> 啊这
> {"res_message": "UserDayFlowOverLimited" , "res code": "UserDayFlowOverLimited"}
> 你账号超出每日上传限制了

没问题了  目前使用正常 好用
